### PR TITLE
Update to Observium 20.9.10731 (21st September 2020) on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by r-daneel**
- Change base image to ubuntu:20.04
- Change to php7.4
- Remove mcrypt support (deprecated)
- Remove libvirt-bin (no need in a container)
- Set Locale to 'C' (LC_ALL=C)

### CODE REVIEW

**Comment by patriciomartinns** [comment]
it seems to me that the project was abandoned by the author

**Comment by r-daneel** [comment]
That's sad, I was using the docker image which worked quiet well.
Well, I'll need to find some time to setup a pipeline and build the docker image from my fork ...
Meanwhile it's there. Feel free to build the docker image and use it :)

**Comment by somsakc** [comment]
Sorry ... for abandon long time ... I updated to ubuntu 20.04, php7.4 and Observium 20.9.10731.

I keep the follows to update soon.  Thank to r-daneel commented
  Remove mcrypt support (deprecated)
  Remove libvirt-bin (no need in a container)
  Set Locale to 'C' (LC_ALL=C)

**Comment by somsakc** [comment]
Again, I missed to look into your amd64/Dockerfile before I did it yesterday. I keep your comment to further update soon. However,  I have todos to enhance this Docker in my plan too. I consider to merge your code and enhance it together. Appreciate and thank for your contribution.

**Comment by r-daneel** [comment]
Hi somsakc, great you're back at it.
Seems my patch is conflicting now.
Feel free to drop this MR and cherry pick needed changes.
Else, I can try to take a bit time to resolve the conflict.
Currently, I'm quiet busy however ;)

**Comment by somsakc** [comment]
Hi r-daneel, yes I merged one pull request from you. And it marks conflicting file for amd64/Dockerfile now. It allow me to do resolve conflicts only. I will correct it if possible. Thank and have good day.

**Pull request closed without merging**
