### PR TITLE
Ubuntu 22.04+observium ce

### PR DESCRIPTION
**Pull request by r-daneel**
These changes update the base image to Ubuntu 22.04 and cleanup the process.  
I removed a couple of packages that are not needed in the context of a container (libvirt) and the community edition (monitoring plugins are useless unless you have a paid version of Observium).  
I also changed the bash script a bit, partly for cosmetic reasons and partly to achieve idempotence on restarts and upgrades.

### CODE REVIEW

**Comment by somsakc** [comment]
Well, I am porting to Ubuntu 22.04 recently with some feature requests if possible. It is good chance to review and merge your pull request. Let me to review for some period of time. Appreciate and thank.

**Comment by somsakc** [comment]
Hi @r-daneel,

I checked back in the [Obsevium installation](https://docs.observium.org/install_debian/). libvirt is required to monitor libvirt vm. It is capable to monitor it with Observium CE. So, I am considering to keep the libvirt-client package for other whom need to monitor vm.

I still keep libphp-phpmailer package, refer to the [issue #20](https://github.com/somsakc/docker-observium/issues/20).

If you have any more feedback, let me know and thank a lot.

**Comment by r-daneel** [comment]
Hi @somsakc 

I am a bit confused by the Observium documentation, as I do not see how the Observium server can possibly 'talk' to a remote libvirt daemon. I'll be doing some testing as I happen to have a proxmox setup. Meanwhile I do not mind including those, it's just a lot of extra stuff. I'll get back with my results ;)
The libphp-phpmailer is ok as well, I just happened to not use it.

Cheers.

**Comment by r-daneel** [comment]
Hi @somsakc 

I added the 2 packages. Should be working now.

**Review by somsakc — APPROVED** [review]
Thank for your contributions to the repository.

**Pull request merged**
