### PR TITLE
Fix observium init tz

### PR DESCRIPTION
**Pull request by r-daneel**
Fix oversight in observium-init.sh script when setting the timezone (TZ).

### CODE REVIEW

**Review by somsakc — APPROVED** [review]
Priority to fix it back as original one.

**Comment by r-daneel** [comment]
Hi @somsakc, any idea on when the fixed image will be up at dockerhub ?

**Comment by somsakc** [comment]
Hi,

Sure, I will do that as soon as possible (target within this coming weekend).
Thank for your remind 😄😄😄.

BG, Somsak C.

________________________________

**Comment by r-daneel** [comment]
Hi @somsakc 
Thanks for the new image push !
Cheers !

**Pull request merged**
